# Discord Creds
DISCORD_APP_CLIENT_SECRET = "Obfascated"
DISCORD_APP_CLIENT_ID = "1194439440714694718"
DISCORD_API_ENDPOINT = "https://discord.com/api/v10"
DISCORD_APP_REDIRECT_URI = "http://localhost:8000/discord/callback"

# General
REDIRECT_URI = "http://localhost:8000"
ERR_REDIRECT_URI = "http://localhost:8000"
RUST_LOG = "none,deckboxtopia=debug"
